version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3306:3306"
    volumes:
      - volume_for_mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 12345
    ports:
      - "6379:6379"
    volumes:
      - volume_for_redis:/data

volumes:
  volume_for_mysql:
  volume_for_redis:
